// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7nGOdbyhvys6O3gShKfAWcZqA3GoOUXI',
    appId: '1:719382982106:web:2812319aa5e7a33ab464e3',
    messagingSenderId: '719382982106',
    projectId: 'hackverse-auth',
    authDomain: 'hackverse-auth.firebaseapp.com',
    storageBucket: 'hackverse-auth.appspot.com',
    measurementId: 'G-BK6CP9FPX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZbBdUKt5vEdRq31GJvGL1SNHMvy6a7Hs',
    appId: '1:719382982106:android:68e930d0ac654b0cb464e3',
    messagingSenderId: '719382982106',
    projectId: 'hackverse-auth',
    storageBucket: 'hackverse-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOQbJJdWayJeq1VsNmOe3CHUXBHMnhPII',
    appId: '1:719382982106:ios:3f3dd8dfcc147882b464e3',
    messagingSenderId: '719382982106',
    projectId: 'hackverse-auth',
    storageBucket: 'hackverse-auth.appspot.com',
    iosClientId:
        '719382982106-4os7tehnbu2d5u32rlkn6g1d4qnnhfap.apps.googleusercontent.com',
    iosBundleId: 'com.example.verseStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOQbJJdWayJeq1VsNmOe3CHUXBHMnhPII',
    appId: '1:719382982106:ios:3f3dd8dfcc147882b464e3',
    messagingSenderId: '719382982106',
    projectId: 'hackverse-auth',
    storageBucket: 'hackverse-auth.appspot.com',
    iosClientId:
        '719382982106-4os7tehnbu2d5u32rlkn6g1d4qnnhfap.apps.googleusercontent.com',
    iosBundleId: 'com.example.verseStore',
  );
}
