name: CI-CD

on:
  push:
    tags:
      - v*

jobs:
  flutter_test:
    name: Flutter analyze, format and test
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter doctor -v

      # Checkout code and get packages.
      - name: Checkout code
        uses: actions/checkout@v3
      - run: flutter pub get -v

      # Analyze, check formatting, and run unit tests.
      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: flutter format --dry-run --set-exit-if-changed .
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json
      # - uses: dorny/test-reporter@v1.4.2
      #   with:
      #     name: test-results
      #     path: test-results.json
      #     reporter: flutter-json
      # - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
      #   with:
      #     min_coverage: 80

  build:
    needs: flutter_test
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: develogo/beerstore:latest

  status_webhook:
    name: Send notification to webhook
    runs-on: ubuntu-latest
    needs:
      - flutter_test
      - build
    if: ${{ always() }}
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "execution-link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}","jobs": [ ${{ toJSON(needs.flutter_test) }}, ${{ toJSON(needs.build) }} ]}'
