name: Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  flutter_test:
    name: Flutter analyze, format and test
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter doctor -v

      # Checkout code and get packages.
      - name: Checkout code
        uses: actions/checkout@v3
      - run: flutter pub get -v

      # Analyze, check formatting, and run unit tests.
      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: flutter format --dry-run --set-exit-if-changed .
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json
      - uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 80
  status_webhook:
    name: Send notification to webhook
    runs-on: ubuntu-latest
    needs: 
      - flutter_test
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "execution-link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}","jobs": [ ${{ toJSON(needs.flutter_test) }} ]}'
      - name: print
        run: echo '${{ toJSON(needs.flutter_test) }}'